[package]
	edition.workspace = true
	name = "data_extractor"
	version = "0.0.0"

[dependencies]
	anyhow = "1"
	clap = { version = "4", features = ["derive"] }
	csv = "1"
	itertools = "0.14"
	serde = { version = "1", features = ["derive"] }
	serde_json = "1"
	serde_repr = "0.1"
